import type { BuildItem } from '../types/randomizer';

export const ITEMS: BuildItem[] = [
  { name: "Abyssal Mask", image: '/img-lol/img-itens-lol/abyssal-mask.png', isBoot: false, isSupportItem: false },
  { name: "Archangel's Staff", image: '/img-lol/img-itens-lol/archangel-s-staff.png', isBoot: false, isSupportItem: false },
  { name: "Ardent Censer", image: '/img-lol/img-itens-lol/ardent-censer.png', isBoot: false, isSupportItem: false },
  { name: "Axiom Arc", image: '/img-lol/img-itens-lol/axiom-arc.png', isBoot: false, isSupportItem: false },
  { name: "Banshee's Veil", image: '/img-lol/img-itens-lol/banshee-s-veil.png', isBoot: false, isSupportItem: false },
  { name: "Black Cleaver", image: '/img-lol/img-itens-lol/black-cleaver.png', isBoot: false, isSupportItem: false },
  { name: "Blackfire Torch", image: '/img-lol/img-itens-lol/blackfire-torch.png', isBoot: false, isSupportItem: false },
  { name: "Blade of the Ruined King", image: '/img-lol/img-itens-lol/blade-of-the-ruined-king.png', isBoot: false, isSupportItem: false },
  { name: "Bloodletter's Curse", image: '/img-lol/img-itens-lol/bloodletter-s-curse.png', isBoot: false, isSupportItem: false },
  { name: "Bloodsong", image: '/img-lol/img-itens-lol/bloodsong.png', isBoot: false, isSupportItem: true },
  { name: "Bloodthirster", image: '/img-lol/img-itens-lol/bloodthirster.png', isBoot: false, isSupportItem: false },
  { name: "Bounty of Worlds", image: '/img-lol/img-itens-lol/bounty-of-worlds.png', isBoot: false, isSupportItem: true },
  { name: "Celestial Opposition", image: '/img-lol/img-itens-lol/celestial-opposition.png', isBoot: false, isSupportItem: true },
  { name: "Chempunk Chainsword", image: '/img-lol/img-itens-lol/chempunk-chainsword.png', isBoot: false, isSupportItem: false },
  { name: "Cosmic Drive", image: '/img-lol/img-itens-lol/cosmic-drive.png', isBoot: false, isSupportItem: false },
  { name: "Cryptbloom", image: '/img-lol/img-itens-lol/cryptbloom.png', isBoot: false, isSupportItem: false },
  { name: "Dawncore", image: '/img-lol/img-itens-lol/dawncore.png', isBoot: false, isSupportItem: false },
  { name: "Dead Man's Plate", image: '/img-lol/img-itens-lol/dead-man-s-plate.png', isBoot: false, isSupportItem: false },
  { name: "Death's Dance", image: '/img-lol/img-itens-lol/death-s-dance.png', isBoot: false, isSupportItem: false },
  { name: "Dream Maker", image: '/img-lol/img-itens-lol/dream-maker.png', isBoot: false, isSupportItem: true },
  { name: "Echoes of Helia", image: '/img-lol/img-itens-lol/echoes-of-helia.png', isBoot: false, isSupportItem: false },
  { name: "Eclipse", image: '/img-lol/img-itens-lol/eclipse.png', isBoot: false, isSupportItem: false },
  { name: "Edge of Night", image: '/img-lol/img-itens-lol/edge-of-night.png', isBoot: false, isSupportItem: false },
  { name: "Essence Reaver", image: '/img-lol/img-itens-lol/essence-reaver.png', isBoot: false, isSupportItem: false },
  { name: "Experimental Hexplate", image: '/img-lol/img-itens-lol/experimental-hexplate.png', isBoot: false, isSupportItem: false },
  { name: "Fimbulwinter", image: '/img-lol/img-itens-lol/fimbulwinter.png', isBoot: false, isSupportItem: false },
  { name: "Force of Nature", image: '/img-lol/img-itens-lol/force-of-nature.png', isBoot: false, isSupportItem: false },
  { name: "Frozen Heart", image: '/img-lol/img-itens-lol/frozen-heart.png', isBoot: false, isSupportItem: false },
  { name: "Guardian Angel", image: '/img-lol/img-itens-lol/guardian-angel.png', isBoot: false, isSupportItem: false },
  { name: "Guinsoo's Rageblade", image: '/img-lol/img-itens-lol/guinsoo-s-rageblade.png', isBoot: false, isSupportItem: false },
  { name: "Heartsteel", image: '/img-lol/img-itens-lol/heartsteel.png', isBoot: false, isSupportItem: false },
  { name: "Hextech Rocketbelt", image: '/img-lol/img-itens-lol/hextech-rocketbelt.png', isBoot: false, isSupportItem: false },
  { name: "Hollow Radiance", image: '/img-lol/img-itens-lol/hollow-radiance.png', isBoot: false, isSupportItem: false },
  { name: "Horizon Focus", image: '/img-lol/img-itens-lol/horizon-focus.png', isBoot: false, isSupportItem: false },
  { name: "Hubris", image: '/img-lol/img-itens-lol/hubris.png', isBoot: false, isSupportItem: false },
  { name: "Hullbreaker", image: '/img-lol/img-itens-lol/hullbreaker.png', isBoot: false, isSupportItem: false },
  { name: "Iceborn Gauntlet", image: '/img-lol/img-itens-lol/iceborn-gauntlet.png', isBoot: false, isSupportItem: false },
  { name: "Immortal Shieldbow", image: '/img-lol/img-itens-lol/immortal-shieldbow.png', isBoot: false, isSupportItem: false },
  { name: "Imperial Mandate", image: '/img-lol/img-itens-lol/imperial-mandate.png', isBoot: false, isSupportItem: false },
  { name: "Infinity Edge", image: '/img-lol/img-itens-lol/infinity-edge.png', isBoot: false, isSupportItem: false },
  { name: "Jak'Sho, The Protean", image: '/img-lol/img-itens-lol/jak-sho--the-protean.png', isBoot: false, isSupportItem: false },
  { name: "Kaenic Rookern", image: '/img-lol/img-itens-lol/kaenic-rookern.png', isBoot: false, isSupportItem: false },
  { name: "Knight's Vow", image: '/img-lol/img-itens-lol/knight-s-vow.png', isBoot: false, isSupportItem: false },
  { name: "Kraken Slayer", image: '/img-lol/img-itens-lol/kraken-slayer.png', isBoot: false, isSupportItem: false },
  { name: "Liandry's Torment", image: '/img-lol/img-itens-lol/liandry-s-torment.png', isBoot: false, isSupportItem: false },
  { name: "Lich Bane", image: '/img-lol/img-itens-lol/lich-bane.png', isBoot: false, isSupportItem: false },
  { name: "Locket of the Iron Solari", image: '/img-lol/img-itens-lol/locket-of-the-iron-solari.png', isBoot: false, isSupportItem: false },
  { name: "Lord Dominik's Regards", image: '/img-lol/img-itens-lol/lord-dominik-s-regards.png', isBoot: false, isSupportItem: false },
  { name: "Luden's Companion", image: '/img-lol/img-itens-lol/luden-s-companion.png', isBoot: false, isSupportItem: false },
  { name: "Malignance", image: '/img-lol/img-itens-lol/malignance.png', isBoot: false, isSupportItem: false },
  { name: "Manamune", image: '/img-lol/img-itens-lol/manamune.png', isBoot: false, isSupportItem: false },
  { name: "Maw of Malmortius", image: '/img-lol/img-itens-lol/maw-of-malmortius.png', isBoot: false, isSupportItem: false },
  { name: "Mejai's Soulstealer", image: '/img-lol/img-itens-lol/mejai-s-soulstealer.png', isBoot: false, isSupportItem: false },
  { name: "Mercurial Scimitar", image: '/img-lol/img-itens-lol/mercurial-scimitar.png', isBoot: false, isSupportItem: false },
  { name: "Mikael's Blessing", image: '/img-lol/img-itens-lol/mikael-s-blessing.png', isBoot: false, isSupportItem: false },
  { name: "Moonstone Renewer", image: '/img-lol/img-itens-lol/moonstone-renewer.png', isBoot: false, isSupportItem: false },
  { name: "Morellonomicon", image: '/img-lol/img-itens-lol/morellonomicon.png', isBoot: false, isSupportItem: false },
  { name: "Mortal Reminder", image: '/img-lol/img-itens-lol/mortal-reminder.png', isBoot: false, isSupportItem: false },
  { name: "Muramana", image: '/img-lol/img-itens-lol/muramana.png', isBoot: false, isSupportItem: false },
  { name: "Nashor's Tooth", image: '/img-lol/img-itens-lol/nashor-s-tooth.png', isBoot: false, isSupportItem: false },
  { name: "Navori Flickerblade", image: '/img-lol/img-itens-lol/navori-flickerblade.png', isBoot: false, isSupportItem: false },
  { name: "Opportunity", image: '/img-lol/img-itens-lol/opportunity.png', isBoot: false, isSupportItem: false },
  { name: "Overlord's Bloodmail", image: '/img-lol/img-itens-lol/overlord-s-bloodmail.png', isBoot: false, isSupportItem: false },
  { name: "Phantom Dancer", image: '/img-lol/img-itens-lol/phantom-dancer.png', isBoot: false, isSupportItem: false },
  { name: "Profane Hydra", image: '/img-lol/img-itens-lol/profane-hydra.png', isBoot: false, isSupportItem: false },
  { name: "Rabadon's Deathcap", image: '/img-lol/img-itens-lol/rabadon-s-deathcap.png', isBoot: false, isSupportItem: false },
  { name: "Randuin's Omen", image: '/img-lol/img-itens-lol/randuin-s-omen.png', isBoot: false, isSupportItem: false },
  { name: "Rapid Firecannon", image: '/img-lol/img-itens-lol/rapid-firecannon.png', isBoot: false, isSupportItem: false },
  { name: "Ravenous Hydra", image: '/img-lol/img-itens-lol/ravenous-hydra.png', isBoot: false, isSupportItem: false },
  { name: "Redemption", image: '/img-lol/img-itens-lol/redemption.png', isBoot: false, isSupportItem: false },
  { name: "Riftmaker", image: '/img-lol/img-itens-lol/riftmaker.png', isBoot: false, isSupportItem: false },
  { name: "Rod of Ages", image: '/img-lol/img-itens-lol/rod-of-ages.png', isBoot: false, isSupportItem: false },
  { name: "Runaan's Hurricane", image: '/img-lol/img-itens-lol/runaan-s-hurricane.png', isBoot: false, isSupportItem: false },
  { name: "Rylai's Crystal Scepter", image: '/img-lol/img-itens-lol/rylai-s-crystal-scepter.png', isBoot: false, isSupportItem: false },
  { name: "Seraph's Embrace", image: '/img-lol/img-itens-lol/seraph-s-embrace.png', isBoot: false, isSupportItem: false },
  { name: "Serpent's Fang", image: '/img-lol/img-itens-lol/serpent-s-fang.png', isBoot: false, isSupportItem: false },
  { name: "Serylda's Grudge", image: '/img-lol/img-itens-lol/serylda-s-grudge.png', isBoot: false, isSupportItem: false },
  { name: "Shadowflame", image: '/img-lol/img-itens-lol/shadowflame.png', isBoot: false, isSupportItem: false },
  { name: "Shurelya's Battlesong", image: '/img-lol/img-itens-lol/shurelya-s-battlesong.png', isBoot: false, isSupportItem: false },
  { name: "Solstice Sleigh", image: '/img-lol/img-itens-lol/solstice-sleigh.png', isBoot: false, isSupportItem: true },
  { name: "Spear of Shojin", image: '/img-lol/img-itens-lol/spear-of-shojin.png', isBoot: false, isSupportItem: false },
  { name: "Spirit Visage", image: '/img-lol/img-itens-lol/spirit-visage.png', isBoot: false, isSupportItem: false },
  { name: "Staff of Flowing Water", image: '/img-lol/img-itens-lol/staff-of-flowing-water.png', isBoot: false, isSupportItem: false },
  { name: "Statikk Shiv", image: '/img-lol/img-itens-lol/statikk-shiv.png', isBoot: false, isSupportItem: false },
  { name: "Sterak's Gage", image: '/img-lol/img-itens-lol/sterak-s-gage.png', isBoot: false, isSupportItem: false },
  { name: "Stormsurge", image: '/img-lol/img-itens-lol/stormsurge.png', isBoot: false, isSupportItem: false },
  { name: "Stridebreaker", image: '/img-lol/img-itens-lol/stridebreaker.png', isBoot: false, isSupportItem: false },
  { name: "Sundered Sky", image: '/img-lol/img-itens-lol/sundered-sky.png', isBoot: false, isSupportItem: false },
  { name: "Sunfire Aegis", image: '/img-lol/img-itens-lol/sunfire-aegis.png', isBoot: false, isSupportItem: false },
  { name: "Terminus", image: '/img-lol/img-itens-lol/terminus.png', isBoot: false, isSupportItem: false },
  { name: "The Collector", image: '/img-lol/img-itens-lol/the-collector.png', isBoot: false, isSupportItem: false },
  { name: "Thornmail", image: '/img-lol/img-itens-lol/thornmail.png', isBoot: false, isSupportItem: false },
  { name: "Titanic Hydra", image: '/img-lol/img-itens-lol/titanic-hydra.png', isBoot: false, isSupportItem: false },
  { name: "Trailblazer", image: '/img-lol/img-itens-lol/trailblazer.png', isBoot: false, isSupportItem: false },
  { name: "Trinity Force", image: '/img-lol/img-itens-lol/trinity-force.png', isBoot: false, isSupportItem: false },
  { name: "Umbral Glaive", image: '/img-lol/img-itens-lol/umbral-glaive.png', isBoot: false, isSupportItem: false },
  { name: "Unending Despair", image: '/img-lol/img-itens-lol/unending-despair.png', isBoot: false, isSupportItem: false },
  { name: "Vigilant Wardstone", image: '/img-lol/img-itens-lol/vigilant-wardstone.png', isBoot: false, isSupportItem: false },
  { name: "Void Staff", image: '/img-lol/img-itens-lol/void-staff.png', isBoot: false, isSupportItem: false },
  { name: "Voltaic Cyclosword", image: '/img-lol/img-itens-lol/voltaic-cyclosword.png', isBoot: false, isSupportItem: false },
  { name: "Warmog's Armor", image: '/img-lol/img-itens-lol/warmog-s-armor.png', isBoot: false, isSupportItem: false },
  { name: "Winter's Approach", image: '/img-lol/img-itens-lol/winter-s-approach.png', isBoot: false, isSupportItem: false },
  { name: "Wit's End", image: '/img-lol/img-itens-lol/wit-s-end.png', isBoot: false, isSupportItem: false },
  { name: "Youmuu's Ghostblade", image: '/img-lol/img-itens-lol/youmuu-s-ghostblade.png', isBoot: false, isSupportItem: false },
  { name: "Yun Tal Wildarrows", image: '/img-lol/img-itens-lol/yun-tal-wildarrows.png', isBoot: false, isSupportItem: false },
  { name: "Zaz'Zak's Realmspike", image: '/img-lol/img-itens-lol/zaz-zak-s-realmspike.png', isBoot: false, isSupportItem: true },
  { name: "Zeke's Convergence", image: '/img-lol/img-itens-lol/zeke-s-convergence.png', isBoot: false, isSupportItem: false },
  { name: "Zhonya's Hourglass", image: '/img-lol/img-itens-lol/zhonya-s-hourglass.png', isBoot: false, isSupportItem: false },
];